# 単回帰分析

## Problem
以下のデータの単回帰分析を行う

| x |  y |
| - |  - |
| 4 | 10 |
| 5 | 12 |
| 8 | 14 |
| 2 |  4 |
| 6 | 10 |

自分で作った簡単な単回帰分析サンプル
エクセルで答えを確認: y = 1.5x + 2.5

In [1]:
import numpy as np

In [2]:
data = np.array([
    [4, 5, 8, 2, 6],
    [10, 12, 14, 4, 10]
    ]).T
data

array([[ 4, 10],
       [ 5, 12],
       [ 8, 14],
       [ 2,  4],
       [ 6, 10]])

In [3]:
features = data[:,0:1]
target = data[:,1:2]
print(features)
print("-" * 10)
print(target)

[[4]
 [5]
 [8]
 [2]
 [6]]
----------
[[10]
 [12]
 [14]
 [ 4]
 [10]]


In [4]:
regressor = np.concatenate([np.ones((features.shape[0], 1)),features], axis=1)
parameter = np.linalg.inv(regressor.T @ regressor) @ regressor.T @ target
print("intercept: ", round(parameter[0, 0], 1), ", slope: ", round(parameter[1, 0], 2))

intercept:  2.5 , slope:  1.5


In [5]:
rmse = np.sqrt(np.mean(np.square(regressor @ parameter - target)))
r_sq = 1 - np.sum(np.square(regressor @ parameter - target)) / (np.sum(np.square(target - np.mean(target))))
print("rmse:", round(rmse, 4), ", r^2:", round(r_sq, 4))

rmse: 1.4832 , r^2: 0.8036
