# 単回帰分析

『永田靖、棟近雅彦．多変量解析法入門．サイエンス社，2001，p.43』の例題をPythonコードで実装 ※解法は書籍に沿っていない

In [1]:
import numpy as np

In [2]:
data = np.array([
    [2.2, 4.1, 5.5,1.9,3.4,2.6,4.2,3.7,4.9,3.2],
    [71, 81, 86, 72, 77, 73, 80, 81, 85, 74]
    ]).T
data

array([[ 2.2, 71. ],
       [ 4.1, 81. ],
       [ 5.5, 86. ],
       [ 1.9, 72. ],
       [ 3.4, 77. ],
       [ 2.6, 73. ],
       [ 4.2, 80. ],
       [ 3.7, 81. ],
       [ 4.9, 85. ],
       [ 3.2, 74. ]])

In [3]:
features = data[:,0:1]  # target = data[:,1] だと1次元配列になってしまうので注意すること
target = data[:,1:2]
print(features)
print("-" * 10)
print(target)

[[2.2]
 [4.1]
 [5.5]
 [1.9]
 [3.4]
 [2.6]
 [4.2]
 [3.7]
 [4.9]
 [3.2]]
----------
[[71.]
 [81.]
 [86.]
 [72.]
 [77.]
 [73.]
 [80.]
 [81.]
 [85.]
 [74.]]


In [4]:
regressor = np.concatenate([np.ones((features.shape[0], 1)),features], axis=1)
parameter = np.linalg.inv(regressor.T @ regressor) @ regressor.T @ target
print("intercept: ", round(parameter[0, 0], 1), ", slope: ", round(parameter[1, 0], 2))
rmse = np.sqrt(np.mean(np.square(regressor @ parameter - target)))
r_sq = 1 - np.sum(np.square(regressor @ parameter - target)) / (np.sum(np.square(target - np.mean(target))))
print("rmse:", round(rmse, 4))
print("r^2:", round(r_sq, 4))


intercept:  61.9 , slope:  4.52
rmse: 1.3154
r^2: 0.934
